### ISSUE TITLE
Glitch wrapping long lines

### ISSUE THREAD

**Issue by fcsonline** [fcsonline/tmux-thumbs#1]

**Comment by isundaylee** [comment]
Have you started working on line-wrapping support? I'd love to take a stab at this, but don't wanna overstep anything that you might already be working on. 

Thanks!

**Comment by fcsonline** [comment]
I have tried to solve this issue many times. Review the list of branches. There are two about this.

**Comment by fcsonline** [comment]
The main problem here is that termbox viewport cuts long lines instead of wrapping them. My approach to solve this issue, knowing the viewport width, is to split long lines manually and _simulate_ a broken line and then run all the tmux-thumbs pattern matching.

**Comment by fcsonline** [comment]
It seems that the termion branch solves this issue too. :muscle:

**Comment by fcsonline** [comment]
Since this PR, this issue is not present any more. 
https://github.com/fcsonline/tmux-thumbs/pull/32
