### ISSUE TITLE
could not find native static library `termbox`

### ISSUE THREAD

**Issue by sherrman** [fcsonline/tmux-thumbs#11]
**Workaround**: libtermbox.a is output into a `target/release/build/termbox-sys-a546bb38dc631cd1/out/lib64` instead of `target/release/build/termbox-sys-a546bb38dc631cd1/out/lib`. So I just made a symlink.

**Problem**: is upstream https://github.com/gchp/termbox-sys/issues/21

```sh
$ cargo build --release
   Compiling termbox-sys v0.2.11
   Compiling regex v1.1.2
   Compiling tempfile v3.0.7
error: could not find native static library `termbox`, perhaps an -L flag is missing?

error: aborting due to previous error

error: Could not compile `termbox-sys`.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by fcsonline** [comment]
Thanks for reporting this. Is this a `tmux-thumbs` or a `rustbox` issue?

Could you checkout `rustbox` and try to compile it? https://github.com/gchp/rustbox

**Comment by sherrman** [comment]
It also fails in rustbox, but it seems to be something in termbox-sys. My reasoning for putting this here is to help anyone else who has run into this and to track the upstream problem.

There's an unmerged fix: https://github.com/gchp/termbox-sys/pull/20

**Comment by fcsonline** [comment]
Ok, we can track news on this issue. 👌

**Comment by fcsonline** [comment]
Closing this issue until news in rustbox project.
