### ISSUE TITLE
Error when activating tmux-thumbs

### ISSUE THREAD

**Issue by mahmoudhossam** [fcsonline/tmux-thumbs#111]
I get the following error when pressing `prefix + space`:

```shell
'~/.tmux/plugins/tmux-thumbs/tmux-thumbs.sh' returned 1
```

Running the script directly doesn't seem to reproduce the problem, and I can't find any other useful logs for tmux.

**Comment by fcsonline** [comment]
Mmmm... Are you using TPM or a cloned repo?

**Comment by fcsonline** [comment]
Mmmm... Are you using TPM or a cloned repo?

**Comment by mahmoudhossam** [comment]
TPM

**Comment by fcsonline** [comment]
Pull the latest changes from master.

More info: https://github.com/fcsonline/tmux-thumbs/commit/30332265138fe728254a180f0977cdbab4ce8b76

**Comment by mahmoudhossam** [comment]
Now the shell script works correctly, but using the keyboard shortcut only makes tmux flicker and nothing happens afterwards.

**Comment by mahmoudhossam** [comment]
Today after restarting the computer the keyboard shortcut also works, thanks for the fix!
