### ISSUE TITLE
[Bug]: install from release tar does not work

### ISSUE THREAD

**Issue by zegervdv** [fcsonline/tmux-thumbs#114]
### What happened?

I install thumbs by downloading the release tar and sourcing the .tmux file in my config. 
You can do this manually by unpacking the tar and running `./tmux-thumbs.sh`.

When I do this with the latest version I run into 2 issues:

1.  The version check fails because cargo.toml cannot be found
2. I need to move the thumb binary under target/release or it seems to crash

I tried adjusting the variables that point to the binaries, but only moving them under target/release seems to work, maybe tmux-thumbs has some hardcoded path to search for the thumbs library?

### Version

0.7.*

### Installation method

Git clone

### Build process

Download a platform binary

### Tmux version

3.3

### Operating System

Linux

**Comment by fcsonline** [comment]
I recently refactored the installation process to have only two options:

- By TPM + precompiled binary (built during a release)
- Git clone + Cargo build

I know that you contributed to this file https://github.com/fcsonline/tmux-thumbs/blob/master/.github/workflows/release.yml, but I wanted to **minimize the amount of ways to install** `tmux-thumbs`, and for me this one is a bit off.

Is a big deal for you to use the TPM approach? If it is, then we can evaluate the options and review how those files are packaged and review if `Cargo.toml` is needed.

**Comment by zegervdv** [comment]
I was assuming that extracting the tarball would work because it contained the `tmux-thumbs.sh` and `tmux-thumbs.tmux` files.

For some reason TPM is not working on some of my setups, so I've given up on that path :)
However, I can work from a git clone + downloading the binary (that seems to work on the latest head).

**Comment by fcsonline** [comment]
Then, closing issue :ok:
