### ISSUE TITLE
Error with tmux-thumbs.sh on OpenBSD

### ISSUE THREAD

**Issue by lcheylus** [fcsonline/tmux-thumbs#115]
On OpenBSD 7.0, I have an error when I try to use the plugin : `'~/.tmux/plugins/tmux-thumbs/tmux-thumbs.sh' returned 1`

After some debug, I fix this issue by modifying the regexp used for grep to get VERSION : 

`VERSION=$(grep 'version =' "${CURRENT_DIR}/Cargo.toml" | grep -oE "[0-9]+\.[0-9]+\.[0-9]+")`

Could you commit this fix please ?

**Comment by fcsonline** [comment]
The problem with this is that this change breaks Linux installation. I'll try to find a compatible approach.

**Comment by fcsonline** [comment]
I think this fixed the problem. Can you confirm?

```bash
grep 'version =' Cargo.toml | grep -o "\".*\"" | sed 's/"//g'
```

**Comment by lcheylus** [comment]
> The problem with this is that this change breaks Linux installation due to the different implementations of `grep`. I'll try to find a compatible approach.

No : on Debian Linux, with GNU grep 3.7, my regexp also works => no incompatibility with different versions of grep on Linux and OpenBSD.

The fix you suggest also works on Linux and OpenBSD.

**Comment by fcsonline** [comment]
I have some systems with grep 3.4, and they will not work with this grep parameter. I think I will choose the `sed` approach.

**Comment by lcheylus** [comment]
Weird, my fix uses a classical extended regexp. Can you try with -F flag (Perl/PCRE regexp) : 

`grep -oF "[0-9]+\.[0-9]+\.[0-9]+"`

**Comment by fcsonline** [comment]
It doesn't work for me. Don't worry about this. The goal is to avoid this kind of problems and I think that the one in the pull request is the best one to not hit it.

This command is just to see if there is a new version that is not in sync with the compiled binary, so it is not a big deal (performance / design implications) how to retrieve the version. Just it has to work. :sweat_smile:

**Comment by lcheylus** [comment]
> It doesn't work for me. Don't worry about this. The goal is to avoid this kind of problems and I think that the one in the pull request is the best one to not hit it.

I made a mistake in my previous post : the correct flag is `-P` (Perl regexp/PCRE), not `-F` (fixed string) : 
`grep -oP "[0-9]+\.[0-9]+\.[0-9]+"`

But it's OK with your fix with sed in the PR.

**Comment by fcsonline** [comment]
Pull request merged! Closing issue. Feel free to reopen it if you have any problem.

**Comment by lcheylus** [comment]
OK, no problem on OpenBSD after upgrade to the last version. Thanks
