### ISSUE TITLE
wayland support

### ISSUE THREAD

**Issue by nrdxp** [fcsonline/tmux-thumbs#12]
any plans?

**Comment by fcsonline** [comment]
No specific plans about this. Do you have some issue running `tmux-thumbs` in Wayland?

**Comment by nrdxp** [comment]
yeah it doesn't work at all. I use a wayland native terminal emulator (alacritty). It would probably work in xwayland but I haven't tried.

**Comment by fcsonline** [comment]
No action items planned for this issue.

Closing issue.
