### ISSUE TITLE
Same shortcut for same text

### ISSUE THREAD

**Issue by ysf** [fcsonline/tmux-thumbs#125]
tmux-thumbs uses a new letter for each new highlight, even if the same text has been found before. Apart from this being different to tmux-fingers and alike, it can happen that with a full screen, the characters become scarce and not everything that can be seen and would've been found otherwise can be highlighted.

It would be great if tmux-fingers could group it's findings before assigning a shortcut.

**Comment by fcsonline** [comment]
You have an option to enable this behavior. Check this out: 

https://github.com/fcsonline/tmux-thumbs#thumbs-unique

Let me know if is this what you are looking for.

**Comment by ysf** [comment]
Thanks a lot for your quick reply, This is indeed was I was looking for. I don't know how I overlooked this. 🤦🏽‍♂️
