### ISSUE TITLE
uppercase-command only print partial results

### ISSUE THREAD

**Issue by pengux** [fcsonline/tmux-thumbs#126]
Example output on screen:
```
/home/peter/test
```

activating tmux-thumbs show hint at the beginning of the path and selecting it will copy the whole path to the clipboard. But when using uppercase hint, only the part `/home/` is printed to the console

**Comment by fcsonline** [comment]
Really weird, because it's the most common use case. Do you have some custom regexp that matches this text?

**Comment by pengux** [comment]
No I don't have any extra regexp that would match it. I tried with another path such as `/foo/bar`. The copy work, but the uppercase command only prints `/foo/ba` (missing `r` at the end)

**Comment by fcsonline** [comment]
Can you paste your tmux-thumbs configuration?

**Comment by pengux** [comment]
Of course, here it is:

````
set -g @plugin 'fcsonline/tmux-thumbs'

run-shell ~/.tmux/plugins/tmux-thumbs/tmux-thumbs.tmux

set -g @thumbs-key j
set -g @thumbs-command 'echo -n {} | wl-copy'
```

I'm using sway on Arch Linux with `tmux 3.3a`

**Comment by fcsonline** [comment]
So, you don't have the `@thumbs-upcase-command` setting configured, right?

**Comment by pengux** [comment]
No, that command is definitely not configured. I did a search in the `.tmux` folder to be sure.

**Comment by fcsonline** [comment]
Can you record a session reproducing the issue, please?

**Comment by pengux** [comment]
Here it is. I think I see the issue now, it's because of the output `Copied /foo/bar/baz` in the status line which interrupt the printing of the output. As soon as you hit another key it prints the rest...

![output](https://user-images.githubusercontent.com/2286687/199667103-afef69e0-1c47-4a09-bc48-f2d0ed6350f8.gif)

**Comment by fcsonline** [comment]
Mmmmm.... Interesting. Can you try to customize the upcase command and remove the part that displays the message?

**Comment by pengux** [comment]
Thank you, yes it works by customizing the command to not displays the message, e.g.:

```
set -g @thumbs-upcase-command 'tmux set-buffer -- {} && tmux paste-buffer && echo -n {} | wl-copy'
```

**Comment by fcsonline** [comment]
Nice!
