### ISSUE TITLE
Copy to system clipboard

### ISSUE THREAD

**Issue by XXiaoA** [fcsonline/tmux-thumbs#128]
Now we have to use `^]` to get the copied text. So how can we copy the selected text into system clipboard?

**Comment by XXiaoA** [comment]
Sorry for ignored the document. I find out the answer
https://github.com/fcsonline/tmux-thumbs#thumbs-command

**Comment by Sleepful** [comment]
@XXiaoA thanks for asking, you helped me find the answer too
