### ISSUE TITLE
Selection is broken in WSL

### ISSUE THREAD

**Issue by sherrman** [fcsonline/tmux-thumbs#13]
Under Windows Subsystem for Linux (running Ubuntu 18), tmux-thumbs hangs when trying to select something.

Repo'd on WSL Terminal, cmder, and the Ubuntu App that WSL ships with. Seems to be unrelated to term emus.

I can hit Enter which changes the prefix/suffix marking of a url or whatever. But once I start pressing keys to select on, the pane freezes. Tmux still responds. I can create a new window and see the tmux-thumbs process running `[...]/.tmux/plugins/tmux-thumbs/target/release/tmux-thumbs --unique --tmux-pane %34`.

Maybe related, but when there are multiple panes on the window, it breaks the pane out in an unexpected way.

I'll try to follow up with more testing using a bare tmux.conf and just tmux-thumbs. There are a couple of small differences in my tmux.conf WSL vs my native linux one (where it works wonderfully).

**Comment by fcsonline** [comment]
Thanks for reporting this. I can't debug under Windows Subsystem, I'm 100% Linux user.

If you can help to debug it, I'll really appreciate it.

**Comment by sherrman** [comment]
Looks like another upstream problem. This time in rustbox: https://github.com/gchp/rustbox/issues/7#issuecomment-433760114

**Comment by fcsonline** [comment]
No action items for this issue. We can reopen it when rustbox move forward in WSL.

Closing issue.

**Comment by gaving** [comment]
Wasted a half hour getting burned by this, hints seem to work then the selection doesn't do anything.

Subscribed to the rustbox thread, will try again if it ever gets implemented.

**Comment by fcsonline** [comment]
Let me know if there is any news.

**Comment by fcsonline** [comment]
Rustbox was replaced with Termion as terminal window manager. Maybe it is time to check it again.

**Comment by sherrman** [comment]
Thanks for the update. It works now and it is **blazing** fast!

**Comment by gaving** [comment]
I'm looking forward to giving this a go ASAP!

**Comment by gaving** [comment]
Working great! Really looking forward to incorporate this into my workflow - thanks @fcsonline! 🙌

**Comment by fcsonline** [comment]
Awesome! :clap:
