### ISSUE TITLE
Path with "$" inside it

### ISSUE THREAD

**Issue by andresgutgon** [fcsonline/tmux-thumbs#131]
<img width="477" alt="image" src="https://user-images.githubusercontent.com/49499/210551294-4dc20141-0d82-4b39-b74c-99d17762bf35.png">

### Expected copy
```
app/routes/notes/\$noteId.tsx
```

### What I get
```
pp/routes/notes
```

I'll let this here and maybe I do the PR : )

**Comment by fcsonline** [comment]
A Pull request will be great! We just need to tweak this regex: https://github.com/fcsonline/tmux-thumbs/blob/760687263d3928a5d1508966329380ecedff7455/src/state.rs#L17

A test would be awesome.

**Comment by fcsonline** [comment]
https://github.com/fcsonline/tmux-thumbs/pull/132

**Comment by fcsonline** [comment]
Merged!
