### ISSUE TITLE
Wrong behavior on long paths

### ISSUE THREAD

**Issue by shahamran** [fcsonline/tmux-thumbs#135]
Hi, and thanks for this great plugin.

I have a problem with long paths - if the path wraps to the terminal width and spans > 1 line, thumbs cuts it at the line end.

![image](https://user-images.githubusercontent.com/10813499/223671484-fac35313-2ef0-4058-b5fa-bf3986dc6391.png)

I think it's possible to solve, since tmux-fingers does the right thing:
![image](https://user-images.githubusercontent.com/10813499/223672334-8fedc10e-abba-493e-91b1-05a3b03d5217.png)

**Comment by fcsonline** [comment]
This is fixed. Check this out: https://github.com/fcsonline/tmux-thumbs/commit/b719e1fb46f140c633ee195ebbd5159b96aedf76
