### ISSUE TITLE
<prefix>-SPACE still activates plugin after @thumbs-key set

### ISSUE THREAD

**Issue by eggbean** [fcsonline/tmux-thumbs#145]
Sometimes, probably a lot of the time, but not all of the time, the default `<prefix>-SPACE` binding still activates the plugin (along with the key that is set).

I have set it like `set -g @thumbs-key '#'`.

At the moment on my local laptop I have this problem but not on a remote server which has the same tmux configuration. I'm will see if this is always the case and try and find the pattern to this intermittent problem.

**Comment by fcsonline** [comment]
Did you try to `unbind` the `space` key? I mean, the reverse of this line:

https://github.com/fcsonline/tmux-thumbs/blob/ae91d5f7c0d989933e86409833c46a1eca521b6a/tmux-thumbs.tmux#LL11C6-L11C14

**Comment by rod-stuchi** [comment]
~I'm using `v0.8.0`, this didn't work~:

    set -g @thumbs-key '#'

~But, this way it worked~:

    bind-key '#' thumbs-pick

**edit:**
for me it is working, I put the `set -g` before the `run-shell ...` line

**Comment by eggbean** [comment]
What `run-shell...` line?

**Comment by rod-stuchi** [comment]
I'm not using a plugin manger

https://github.com/fcsonline/tmux-thumbs/blob/master/README.md?plain=1#L74

**Comment by eggbean** [comment]
Oh, okay. I don't think I have this problem any more, but I don't remember how it was fixed.
