### ISSUE TITLE
`pbcopy` does not seem to work

### ISSUE THREAD

**Issue by meain** [fcsonline/tmux-thumbs#17]
I tried setting

```
set -g @thumbs-command 'pbcopy'
```

but when I use it, it makes by clipboard blank. From what I can understand, pbcopy is invoked but the value is not getting passed.

I am using tmux version `3.0` and not using `tmux-yank` plugin.

**Comment by fcsonline** [comment]
I just realized that the documentation was wrong. `pbcopy` requires to provide the content that you want to copy as an input pipe.

I created this PR to fix this. Could you test it, please? Don't forget to change the `tmux.conf`

https://github.com/fcsonline/tmux-thumbs/pull/18

**Comment by fcsonline** [comment]
Could you check the new stuff merged in master, please?

**Comment by meain** [comment]
Hey @fcsonline , it still does not work for me.

I have some clue about what the issue is though. I don't think piping works with how it is handled right now. I created a script `copy` with the contents as below and I gave that script as the thumbs command. It works this way.

```sh
# /usr/bin/copy
echo "$1" | pbcopy
```

```tmux
set -g @thumbs-command 'copy {}'
```

**Comment by fcsonline** [comment]
I have been playing with the last commits in master and pipes works fine. 😕 

About the extra stuff, could you build a reproducible test case in `samples`, please?

**Comment by meain** [comment]
Hey, my bad. It works now. I did `cargo build` instead of `cargo build --release` after pulling the new one.

**Comment by meain** [comment]
btw, you might wanna change the example to 

```
echo -n {} | pbcopy
```

OR

```
printf {} | pbcopy
```

Or there will be an extra space at the end.

**Comment by fcsonline** [comment]
Yep! Thanks!
