### ISSUE TITLE
Thumbs does not take scroll position into account

### ISSUE THREAD

**Issue by rakanalh** [fcsonline/tmux-thumbs#22]
Hello!

Thanks alot for making this package... it's definitely alot faster than fingers.

However, when you have a long buffer that you scroll to where you want to copy text, thumbs would only display the end of scroll buffer rather than take the currently displayed lines and displaying those. I believe fingers has this issue resolved by querying tmux about current scroll position.

**Comment by fcsonline** [comment]
Thanks for reporting this issue.

I will investigate how to do that to be able to fix it.

**Comment by fcsonline** [comment]
I just add support for scroll/copy mode in this PR:

https://github.com/fcsonline/tmux-thumbs/pull/23

It's merged in master. Check it out! :ok_hand:

**Comment by rakanalh** [comment]
Many thanks @fcsonline

**Comment by fcsonline** [comment]
Closing issue! :muscle:
