### ISSUE TITLE
Integration with tmux-open

### ISSUE THREAD

**Issue by dufferzafar** [fcsonline/tmux-thumbs#24]
Is there a way I can have the matching file paths open in the editor, rather than being copied to the clipboard!?

https://github.com/tmux-plugins/tmux-open

**Comment by fcsonline** [comment]
You can customize the `@thumbs-command` and `@thumbs-upcase-command` to do whatever you want.

More information here: 

https://github.com/fcsonline/tmux-thumbs#thumbs-command

**Comment by iryan2** [comment]
> You can customize the `@thumbs-command` and `@thumbs-upcase-command` to do whatever you want.
> 
> More information here:
> 
> https://github.com/fcsonline/tmux-thumbs#thumbs-command

Sorry to revive an old thread, thought it'd be better than creating a new issue.

I'm wondering if you could tell me what I'm doing wrong. When I set

```
set -g @thumbs-upcase-command 'vim {}'
```

Nothing happens.

However, I can see that the upcase command works with the below configuration. That is, I get the expected thing on my system clipboard. 
```
set -g @thumbs-upcase-command 'echo -n {} | pbcopy'
```

Does the command run in a subshell or something? That would explain the behaviour I'm seeing, but how would I configure it to actually open the file in vim? 

Edit: I suppose a different way of asking this question is - what's supposed to happen when the command is set like so: 
```
set -g @thumbs-upcase-command 'echo -n {}'
```

I would have expected the filename of the match I chose to be output in the terminal, but given this doesn't happen I'm starting to suspect I have some kind of fundamental misunderstanding of the nature of this plugin. Thanks in advance for your help.
