### ISSUE TITLE
Provide binary releases?

### ISSUE THREAD

**Issue by dufferzafar** [fcsonline/tmux-thumbs#25]
I don't code in Rust, but I still love the language simply because of all the goodies that I find - I can just download the binary and use them. 

Furthermore, you could also have a method of plugin installation via TPM?

**Comment by fcsonline** [comment]
I'm not sure if this is what you want but you can install the standalone version of `thumbs` with the steps described here:

https://github.com/fcsonline/tmux-thumbs#standalone-thumbs

Regarding TPM, I can add some information how to do it 👌

**Comment by dufferzafar** [comment]
That requires me to have cargo etc. setup, right?

**Comment by fcsonline** [comment]
Yep. I think there is no shorter alternative to install Rust applications.

**Comment by fcsonline** [comment]
Closing issue.
