### ISSUE TITLE
Not working at all

### ISSUE THREAD

**Issue by windowsrefund** [fcsonline/tmux-thumbs#30]
I'm running tmux 2.9a with this plugin freshly installed via TPM. After hitting prefix+space, I see this
`
]4;0;#08090B\]4;1;#a3576b\]4;2;#5676a1\]4;3;#ac667e\]4;4;#5e73a8\]4;5;#bc82a2\]4;6;#cfa9a5\]4;7;#dfe4e3\]4;8;#9c9f9e\]4;9;#a3576b\]4;10;#5676a1\]4;11;#ac667e\]4;12;#5e73a8\]4;13;#bc82a2\]4;14;#cfa9a5\]4;15;#dfe4e3\]10;#dfe4e3\]11;#08090B\]12;#dfe4e3\]13;#dfe4e3\]17;#dfe4e3\]19;#08090B\]4;232;#08090B\]4;256;#dfe4e3\]708;#08090B\
`

**Comment by fcsonline** [comment]
Could you give us a bit more of context?

**Comment by fcsonline** [comment]
Feel free to reopen it with more details, please

**Comment by benswinburne** [comment]
This happens to me too. What information can i provide to help which may be useful?

Just tried it on tmux `3.0a` and `3.1b`. Installed with tmux plugin manager.

**Comment by fcsonline** [comment]
Which terminal do you use? One thing you can try is to go to the installation folder an try running de standalone version `thumbs` piping some buffer to know it works:

`cat samples/test1 | cargo run --bin thumbs`
