### ISSUE TITLE
default path pattern doesn't capture the tilde

### ISSUE THREAD

**Issue by avshyz** [fcsonline/tmux-thumbs#34]
As the title mentions, this is a small bug, but - 
Whenever I try to run thumbs (using termion's branch, compiling from source on OSX), instead of capturing the whole path, thumbs omits the ~ at the beginning (if it's there).

**Comment by fcsonline** [comment]
This commit in the branch will fix it:
https://github.com/fcsonline/tmux-thumbs/pull/32/commits/7ff79fdea474b712a5d50a126fadad88a4014f88

**Comment by fcsonline** [comment]
This branch was merged and includes the mentioned commit:

https://github.com/fcsonline/tmux-thumbs/pull/32

Closing the issue. Feel free to reopen it if it doesn't work as expected.
