### ISSUE TITLE
Debug hints?

### ISSUE THREAD

**Issue by vkrishnaswam** [fcsonline/tmux-thumbs#38]
I'm trying to use this with WSL using tmux-2.9a, using zsh. 
I've installed this using TPM and I can see this directory cloned into the plugins directory. 

When I hit `prefix + space` nothing really happens. How can I debug this further? 
Any hints would be useful. 

Thanks.

**Comment by fcsonline** [comment]
Sometimes, the compilation of `tmux-thumbs` takes a while and there is no feedback. Try to go to the folder where TPM check outs the plugin to know is the `thumbs` binary is there.

**Comment by fcsonline** [comment]
This commit https://github.com/fcsonline/tmux-thumbs/commit/0cf29dd94265dc24a8ee59d1aa0870ac2a5963b8 show what it is going on under the hood during the first period of time when the package is been compiled.

Closing issue.

**Comment by gaving** [comment]
@vkrishnaswam I periodically check in hoping for WSL support, but it's not looking likely any time soon due to this open issue (outside tmux-thumbs):- https://github.com/fcsonline/tmux-thumbs/issues/13#issuecomment-545201053

**Comment by fcsonline** [comment]
Rustbox was replaced with Termion as terminal window manager. Maybe it is time to check it again.

**Comment by gaving** [comment]
@fcsonline Oh really, nice! Will check on my work machine tomorrow and report back.
