### ISSUE TITLE
Panic when nothing "hintable" in the screen

### ISSUE THREAD

**Issue by augustobmoura** [fcsonline/tmux-thumbs#39]
Using it with a no hintable elements flashes a panic message
![issue-thumbs-2020-05-15_11 57 08](https://user-images.githubusercontent.com/5845160/82065352-631efe80-96a4-11ea-807e-242ee098c6ef.gif)

Zipped mkv video: 
[issue-thumbs-2020-05-15_11.57.08.zip](https://github.com/fcsonline/tmux-thumbs/files/4635132/issue-thumbs-2020-05-15_11.57.08.zip)

**Comment by fcsonline** [comment]
Good catch! Classic simple case.

**Comment by fcsonline** [comment]
Fixed in this commit https://github.com/fcsonline/tmux-thumbs/commit/2bb8900e6b669119f15a1a5adb34099375c0b8c3. Let me know if it is fixed for you too.

**Comment by augustobmoura** [comment]
Still flashing a panic

![issue-thumbs-2020-05-25_18 12 02](https://user-images.githubusercontent.com/5845160/82843488-a3a42680-9eb3-11ea-9179-8102995c0aac.gif)

**Comment by fcsonline** [comment]
I can't reproduce it. Also, the `unwrap` line I can read in this gif is `src/view.rs:156` and this was exactly the line I fixed and right now there are no unwraps there. Did you compile after checking out the commit? Try doing a `cargo build && cargo build --release`

**Comment by augustobmoura** [comment]
Yeah it was missing a rebuild, I thought tpm would rebuild it automatically. Closing it
