### ISSUE TITLE
Feature request :: tmux popup integration

### ISSUE THREAD

**Issue by lcrockett** [fcsonline/tmux-thumbs#41]
Using your plugin with great pleasure, cheers for that !

Any chance it will be expanded in the future to support tmux's (+3.2) new popup functonality ? As an additional option or instead of using tmux's [`new-window`](https://github.com/fcsonline/tmux-thumbs/blob/d2f765bae8373baf89f48241cc7a1b329368f69d/src/swapper.rs#L198).

See also other resources related to this feature:
[`https://github.com/tmux/tmux/issues/1842`](https://github.com/tmux/tmux/issues/1842)
[`https://github.com/kevinhwang91/fzf-tmux-script`](https://github.com/kevinhwang91/fzf-tmux-script)

**Comment by fcsonline** [comment]
No plans in the short term. Feel free to create a prototype and open a pull request! :muscle:

**Comment by pbartyik** [comment]
@lcrockett how do you imagine this behaviour? Would it be presented in a full-screen popup with existing screen (e.g. same as in a new window now, only in a popup), or matches listed in the popup to be searched with fzf, something else?

**Comment by lcrockett** [comment]
@pbartyik I would imagine the results to be displayed in a 90% window filling pop-up pane as to be able to use more of the available screen estate.

**Comment by fcsonline** [comment]
I'm not sure to get the idea. One of the basic features of tmux-thumbs is to show the hints exactly on top of the match. I don't get where the pop-up pane would live.

**Comment by fcsonline** [comment]
Is here some action item?

**Comment by kurktchiev** [comment]
i think this is less tmux-thumbs enhancement and more its own separate plugin that would wrap something like the buffer list, to allow you to get a nice popup with a “clipboard history” that you can then search/choose/etc super fast and much less disruptive than current listing. 

this is just my guess though

**Comment by lcrockett** [comment]
On second thought, I agree with @kurktchiev. This plugin works best without an overlay and i'm happily using it this intended way.

**Comment by fcsonline** [comment]
Ok! 👌
