### ISSUE TITLE
Cargo build output target issue

### ISSUE THREAD

**Issue by zbrox** [fcsonline/tmux-thumbs#42]
The cargo build command here: 
https://github.com/fcsonline/tmux-thumbs/blob/0cf29dd94265dc24a8ee59d1aa0870ac2a5963b8/tmux-thumbs.tmux#L14

should have the extra parameter `--target-dir=target` since the binary has a hardcoded path to the `target` folder in the working folder and for some environments `CARGO_TARGET_DIR` is set to something else.

**Comment by fcsonline** [comment]
Good catch! Can you create a pull request, please?
