### ISSUE TITLE
Multiline Custom Regex

### ISSUE THREAD

**Issue by JSteeleIR** [fcsonline/tmux-thumbs#44]
Hey, love this plugin, it's fantastic!

I don't know rust (yet) otherwise I'd try and do it myself, but is there anyway to implement a 'multiline' regex? 

I end up wanting to yank big, formatted multi-line SQL statements quite often... Being able to grab anything matching `/^SELECT(?:.[\n\r]*)*;/Ug` would be phenomenal.

Any rough idea if this would be possible with the current implementation, or how much effort it would take to make it possible?

**Comment by JSteeleIR** [comment]
Looking at [this line](https://github.com/fcsonline/tmux-thumbs/blob/9416da2579ca1a0557fb89ab66040b410d34aebb/src/state.rs#L89), it looks like we're iterating line-by-line over the passed buffer, which would be incompatible with a multiline regex, IIUC. :(

**Comment by fcsonline** [comment]
You are right, we are iterating line by line and then match patterns. It will not be possible without a big refactor how we process the incoming buffer. I think, in this case, the classic tmux selection is the best option. :/

**Comment by fcsonline** [comment]
Closing because the refactor it is huge.
