### ISSUE TITLE
flickering display

### ISSUE THREAD

**Issue by pbartyik** [fcsonline/tmux-thumbs#45]
Running tmux git and fully upgraded tmux-thumbs, behold the flickering in alacritty :)
Would it be possible for tmux-thumbs to not constantly re-draw the "overlay"?
![flickering](https://user-images.githubusercontent.com/39059618/87070072-900d0f00-c218-11ea-806d-672cbd7a6bc2.gif)

**Comment by pbartyik** [comment]
commenting out https://github.com/fcsonline/tmux-thumbs/blob/master/src/view.rs#L248 does the trick but then we don't have nice highlights when moving with arrow keys.

**Comment by stevenrchun** [comment]
+1 also experiencing this

**Comment by pbartyik** [comment]
the pull request I created for this isn't commenting out the rendering, just skipping it if nothing new to show. Still renders when selection is moved with the arrow keys.
@stevenrchun can you check if #46 works for you?

**Comment by fcsonline** [comment]
Check out master to get the improvements!
