### ISSUE TITLE
contrast causes whole line to be in brackets

### ISSUE THREAD

**Issue by pbartyik** [fcsonline/tmux-thumbs#47]
set -g @thumbs-contrast 1 puts brackets not only around hints but whole line
```
[   [d]nk/loopback[f]:00:00:00:00:00]brd[q]:00:00:00:00:00]
```

I think due to [view.rs#92](https://github.com/fcsonline/tmux-thumbs/blob/master/src/view.rs#L92)

**Comment by fcsonline** [comment]
Thanks for the contribution!
