### ISSUE TITLE
Which versions of tmux are supported?

### ISSUE THREAD

**Issue by jugglerchris** [fcsonline/tmux-thumbs#5]
I just tried it with tmux 1.8; I had to adjust the quoting (the command given to `tmux new-window` had to be one word) and then it killed the tmux server.  :-)

I can look into it when I get some spare time, but if the answer is "upgrade tmux" then I should just do that.

**Comment by fcsonline** [comment]
I execute `tmux` 2.6. We can review/tweak the behaviour for other versions. 👌

**Comment by fcsonline** [comment]
I added a new section in the Readme file about tmux compatibility. We can add more information there.

Closing this issue.
