### ISSUE TITLE
Nothing happens wheen using inside kitty and $TERM is xterm-kitty

### ISSUE THREAD

**Issue by dagadbm** [fcsonline/tmux-thumbs#53]
Literally nothing happens.

Is it easy to fix? I have no idea how to even start debugging this.

**Comment by fcsonline** [comment]
Can you give me more context?

- Which tmux version do you have?
- Did you use TPM?
- Did you see a compilation window building with cargo?
- Do you have tmux-thumbs installed? Can you run `thumbs` standalone version?

This will help me to understand what is going on.

**Comment by dagadbm** [comment]
tmux -V
tmux 3.1b

I used TPM yes here is the tmux.conf I am currently using:
https://github.com/dagadbm/dotfiles/blob/master/tmux/tmux.conf
I also use some vim plugin that changes the color of tmux to be the same as onedark vim

I don't have thumbs installed I only did the tmux-thumbs install using tpm.

I press ctrl+F or ctrl+space and i dont see anything on the screen (its like the command doesnt run)

I dont really know how I can do to debug this though. How can I help?

**Comment by fcsonline** [comment]
Can you go to your tmux plugins folder and search for `tmux-thumb` and then check if the binaries `target/release/tmux-thumbs` and `target/release/thumbs` arre there?

**Comment by dagadbm** [comment]
oh...
weird. i dont have a target folder..

maybe I am missing some step?  am i supposed to build the project manually?

**Comment by dagadbm** [comment]
well.. i dont have cargo installed.. let me see if having it solves the issue (i thought this already had a pre compiled executable)

**Comment by dagadbm** [comment]
yup. now its installing and building things.

can you add to the README you need to have rust/cargo installed? (i used asdf but im sure most people wont use that)

**Comment by dagadbm** [comment]
sorry for the spam. so here are my suggestions from the order I think makes it easier to have more people using this:

add the rust target binary on  your github repo so users dont have to build it
make it clear rust/cargo is a required dependency both on the manual install and on the plugin manager install

**Comment by fcsonline** [comment]
Maybe I can add more details about this, but there is a step where I talk about cargo [here](https://github.com/fcsonline/tmux-thumbs#tmux-integration).

Not a big fan of adding binaries directly to releases. For security reasons, I prefer to have to build the binary by yourself. You never know what a binary includes :wink:

**Comment by dagadbm** [comment]
I do know you have that section there, the problem is since I use the
plugin manager I assumed the previous section was handled automatically by
the plugin manager but yeah now I see it was my problem.
So maybe add a section prior to that one so people know they must have
rust/cargo installed on their system (maybe suggest asdf in the process :P)

**Comment by fcsonline** [comment]
Ok, got it. I will add a list of prerequisities. :+1:
