### ISSUE TITLE
osc52 does not work

### ISSUE THREAD

**Issue by pbartyik** [fcsonline/tmux-thumbs#54]
Connecting to remote linux box via ssh running tmux and latest tmux-thumbs.
Doing `echo -e "\033]52;c;$(base64 <<< hello)\a"` gets `hello` into the system's clipboard which is running the terminal, so OSC52 works with the terminal.
When enabling OSC52 in tmux-thumbs the copied data does not get propagated back to the system's clipboard, but the following gets printed (if copying 1.1.1.1): `Ptmux;]52;0;MS4xLjEuMQ==\`

Edit:
tmux `next-3.3`
tmux-thumbs: 3415117b

**Comment by gaving** [comment]
I can reproduce this myself:-

```
printf $'\e]52;c;%s\a' "$(base64 <<<'hello world')"
```

copies to the system clipboard fine, but when enabling osc52 I'm getting the following printed and paged:-

![image](https://user-images.githubusercontent.com/43741/91770009-53d2ab00-ebd8-11ea-87b1-8f070eca9644.png)

Tried to enable some terminal-overrides to get this going to no effect:-

```
set -as terminal-overrides ',tmux*:Ms=\\E]52;%p1%s;%p2%s\\007'
set -as terminal-overrides ',screen*:Ms=\\E]52;%p1%s;%p2%s\\007'
set -s set-clipboard on
set -g @thumbs-osc52 '1'
```

Latest tmux-thumbs, tmux 3.1b.

**Comment by pbartyik** [comment]
```rust
fn main() {
  let x = "hello";
  let b_x = base64::encode(x.as_bytes());
  let o_seq = format!("\x1b]52;0;{}\x07", b_x);
  println!("{}", o_seq);
}
```
works, thinking this has to do with tmux?

**Comment by gaving** [comment]
Nice debugging + patch, honestly wouldn't have known where to start! 😆

**Comment by pbartyik** [comment]
thanks :) now we just need to be patient until tmux merges that patch. Or clone, patch and install like I did.

**Comment by pbartyik** [comment]
closing as custom command can do this.

**Comment by listx** [comment]
I still get the behavior described in https://github.com/fcsonline/tmux-thumbs/issues/54#issuecomment-684052958. Does anyone else experience it as well?

Also, I don't understand the workaround. What is the custom command that I must use, and how do I configure it in my tmux.conf?

I'm on the latest tmux-thumbs with tmux 3.2a.

**Comment by peter-bartyik** [comment]
this is what I have in my .tmux.conf, you'll need a recent enough tmux instance tho.
```
set -g @thumbs-command 'tmux set-buffer -w "{}"'
set -g @thumbs-upcase-command 'tmux set-buffer -w "{}" && tmux paste-buffer'
