### ISSUE TITLE
thumbs-regexp-N incorrect match

### ISSUE THREAD

**Issue by pbartyik** [fcsonline/tmux-thumbs#56]
in `.tmux.conf` 
```
set -g @thumbs-regexp-1 'Vlan\d+'
```

Example text to be matched:
```
Vlan1
Vlan23
Vlan999
```
Only matches `Vlan` and ignores the digits

**Comment by fcsonline** [comment]
Maybe you need to escape the backslash? I have fo example this one and it works properly:
```
set -g @thumbs-regexp-2 '[a-f0-9]{2}:[a-f0-9]{2}:[a-f0-9]{2}:[a-f0-9]{2}:[a-f0-9]{2}:[a-f0-9]{2}:' # Match MAC addresses
```

**Comment by pbartyik** [comment]
this is interesting, escaping does not help. I've also tried `Vlan[0-9]' `Vlan[0-9]{2}` `Vlan\d` and none matched the digit(s).

**Comment by fcsonline** [comment]
Ok, I had a bit of time to test and now I understand what was going on. The standard `ipv6` matcher was matching mac address so, my custom regexp for them was not doing anything. Then I testes the email one and it is not working either. As you detect, there is a regression here.

```
set -g @thumbs-regexp-1 '[a-z]+@[a-z]+.com' # Match emails
set -g @thumbs-regexp-2 '[a-f0-9]{2}:[a-f0-9]{2}:[a-f0-9]{2}:[a-f0-9]{2}:[a-f0-9]{2}:[a-f0-9]{2}:' # Match MAC addresses
```

I'm going to investigate a bit more and review you pull request to know in which point the custom regexp are broken.

**Comment by fcsonline** [comment]
Ok, I found the problem. The problem was in the `swapper.rs` file. Can you check this commit out? https://github.com/fcsonline/tmux-thumbs/commit/cf009d36102ceadf7011b5bd3a9cdf216326463c

It is in master right now.

**Comment by pbartyik** [comment]
thanks for merging!
