### ISSUE TITLE
Worse url isolation than tmux-fingers

### ISSUE THREAD

**Issue by mimadrid** [fcsonline/tmux-thumbs#6]
tmux-thumbs is awesome specially the autopaste feature 
But it has more problem isolating urls than tmux-fingers
Check this file for example https://raw.githubusercontent.com/mimadrid/.dotfiles/master/README.md
Here you have the screenshot with tmux-fingers on the left and tmux-thumbs on the right
Thanks a lot in advance and I hope to be useful
Don't hesitate to request more information
![thumbs](https://user-images.githubusercontent.com/3269878/57032167-fd530680-6c49-11e9-841c-f54b0940510f.png)

**Comment by fcsonline** [comment]
I was able to reproduce the bug and was something related with the paths pattern. I just pushed some changes to fix that and more changes to support markdown urls. Give it a try.

**Comment by mimadrid** [comment]
Awesome work @fcsonline !
Now it's almost perfect except for:
<https://github.com/mimadrid/.dotfiles/fork>
(./bin/.bin/dropbox-urls-extractor,)
(./tmux/.tmux.conf)

**Comment by fcsonline** [comment]
I just pushed some changes. Check this out.

**Comment by mimadrid** [comment]
Spectacular work @fcsonline!
Thanks so much
