### ISSUE TITLE
extended regexp options

### ISSUE THREAD

**Issue by pbartyik** [fcsonline/tmux-thumbs#60]
Would be nice to have extended options for regular expressions. Currently I can match anything but `"`. I'd like to also match regexp around specific keywords.

For example a cisco config might contain
```
route-map blahblah seq 10 permit
```
The keyword I'd like to match here is `blahblah`, possible regexp for that is `group(1)` of `^\s*route-map\s+(\S+)\s+.+`

tmux config would need to pass to thumbs which group is to be matched, for example
```
@thumbs-regexp-extended-1-group-1
```
where first `1` is the number of regexp to be able to create more than one, `group-1` would specify which group to match

Would also need to figure out how to highlight only the group matched part of the output and not the whole string matched with regexp.

Thoughts?

**Comment by fcsonline** [comment]
Mmmmm... I'm not sure it is needed. I had more or less the same use case in this pattern:

https://github.com/fcsonline/tmux-thumbs/blob/fc6d5833a32e7a4d73c85be6712512a6b47cea69/src/state.rs#L10

tmux-thumbs will try to extract always the first captured group. Not sure why in your case doesn't work.

**Comment by pbartyik** [comment]
I didn't know that, thanks! :)

**Comment by fcsonline** [comment]
Maybe we can document it. :sweat_smile:
