### ISSUE TITLE
ISSUE: tmux 's resize-pane will reset when call tmux-thumbs

### ISSUE THREAD

**Issue by YongHaoWu** [fcsonline/tmux-thumbs#62]
I want to keep the pane as origin. Is there any hook or trick to do this?

Thanks.

**Comment by pbartyik** [comment]
there is a good chance #67 fixes this too, can you give it a shot?

**Comment by YongHaoWu** [comment]
@pbartyik Thanks, had looked the PR, LGTM.   I'll give a try when it is merged, lol.

**Comment by fcsonline** [comment]
It is merged! Let us know @YongHaoWu

**Comment by YongHaoWu** [comment]
> It is merged! Let us know @YongHaoWu

Works good for me now, thanks!
