### ISSUE TITLE
BUG: zoomed panes get unzoomed

### ISSUE THREAD

**Issue by nkh** [fcsonline/tmux-thumbs#63]
hitting prefix + space in a zoomed pane, unzooms it making this pretty cool plugin value drop significantly.

**Comment by fiskhest** [comment]
Seeing the same problem, even when rebinding, since I also wanted to restore the original bind behavior:

```
set -g @thumbs-key F
unbind Space
bind-key Space next-layout
```

**Comment by pbartyik** [comment]
came to report the same, seems I was slow :) not quite sure how this part exactly works.
I'm thinking this'll be due to something around here:
https://github.com/fcsonline/tmux-thumbs/blob/master/src/swapper.rs#L195

**Comment by pbartyik** [comment]
yeah that was half of it :) can you check the fork to see if it is working for you too?

**Comment by fiskhest** [comment]
@pbartyik working perfectly, great work! :100:

**Comment by pbartyik** [comment]
@nkh can you please test with latest and see if it works?

**Comment by nkh** [comment]
removed the plugin and re-installed, work fine; good work I can now enable it :)
