### ISSUE TITLE
Selection window is not switched to automatically

### ISSUE THREAD

**Issue by MunifTanjim** [fcsonline/tmux-thumbs#68]
After pressing `<prefix>+<space>` the selection windows (`2: [thumbs]`) is opened but not switched to automatically. I have to manually press `<prefix>+2` to see it.

![Peek 2020-11-07 11-54](https://user-images.githubusercontent.com/8050659/98433350-5aa5fe80-20f0-11eb-8559-126f82b8358a.gif)

This is happening with the latest `tmux-thumbs`.

Tmux version: `3.0a-2ubuntu0.2`

**Comment by fcsonline** [comment]
Sorry @MunifTanjim for this late answer, I have been really busy this month. It seems a regression introduced by this commit https://github.com/fcsonline/tmux-thumbs/commit/7da1b8edadf79bbf1349532c5ab4eaf65b39d181

I'm talking to @pbartyik in this pull request about this: https://github.com/fcsonline/tmux-thumbs/pull/67

**Comment by fcsonline** [comment]
I just added this commit that fixes this problem.

https://github.com/fcsonline/tmux-thumbs/commit/c4ce3689041985ca1bee1387cbaf4403a0e349c6

Feel free to reopen the ticket if it is not working for you

**Comment by nandkeypull** [comment]
I had the same problem and this commit fixed it for me. Thank you, it works great now!

**Comment by x4121** [comment]
I think I'm experiencing the same issue.
I'm running alacritty `0.6.0` with tmux `3.0a` and thumbs `0.5.0`. Thumbs still opens the selection in a new window called `[thumbs]`.

I thought it might be related to the tmux version, so I installed `3.1c`. In this tmux version nothing seems to happen when pressing the "thumbs"-hotkey. No new window opens, but I also don't see the highlighting.

**Comment by fcsonline** [comment]
Can you test last version of thumbs?

**Comment by x4121** [comment]
The tmux plugin is installed with tpm (and was already on the current master), I tried to build and install the rust binary from git but I get the same behavior (for tmux `3.0a` and `3.1c`). I also get the same behavior in alacritty and gnome-terminal.
I also have this behavior in tmux-thumbs `0.4.4` and `0.4.0`, so it might be completely unrelated to the regression mentioned :confused:
