### ISSUE TITLE
Invoking tmux-thumbs in maximized pane unmaximizes the pane

### ISSUE THREAD

**Issue by philippotto** [fcsonline/tmux-thumbs#71]
Steps to reproduce:

- open a tmux window with multiple panes
- maximize a pane (by default tmux-prefix-z)
- invoke tmux-thumbs via 
- now, the current pane is unmaximized automatically which makes large parts of the pane output invisible (due to the decreased space). invoking the thumbs-action by hitting a letter still works, though.
- the thumbs-mode is exited, but the pane is still unmaximized.

I'm using tmux 2.3 which might be the reason for this? Other than that, the plugin seems to work fine :+1: I just wanted to open a PR to update the compatibility table before I ran into this issue. Nevertheless: awesome package :+1:

**Comment by fcsonline** [comment]
Thanks for the report! I was able to reproduce it on tmux 3.0.

I will investigate if there is some solution.

**Comment by fcsonline** [comment]
@philippotto I was able to fix the problem. :muscle: Could you check this out, please?

https://github.com/fcsonline/tmux-thumbs/pull/72

**Comment by philippotto** [comment]
Awesome, works for me now :tada: Thanks for fixing this so quickly!

**Comment by fcsonline** [comment]
Awesome! 👌
