### ISSUE TITLE
[Feature Request] ability to disable default regex

### ISSUE THREAD

**Issue by gjeusel** [fcsonline/tmux-thumbs#78]
Hey there,

I would really appreciate the capability to disable some pre-defined regex. And more specifically the "Numbers ( 4+ digits )".

Indeed, while adding some custom regex to match http url: 
```
set -g @thumbs-regexp-1 'https?://.+?:?[0-9]*?\b' # Match files
```

I found myself not being able to catch "http://localhost:8000" as it only matches the "8000".

**Comment by gjeusel** [comment]
Nevermind, my bad (getting used to rust regex)

**Comment by pavoljuhas** [comment]
@fcsonline - could you please consider this feature?

An extra `--disable-default-regexp` option would allow to match only the pattern set with the --regexp option, e.g., only URLs or only files in the current directory.  This is currently not possible without highlighting extra items (numbers, hashes, etc.) on the screen.
