### ISSUE TITLE
BUG: zoomed pane selection is not for the whole pane

### ISSUE THREAD

**Issue by nkh** [fcsonline/tmux-thumbs#80]
given:
   a window with two panes A and B
   A size 20 lines, B size 30 lines
   B gets zoomed to the full 50 lines
   running tmux-thumb displays 30 lines to pick from, IE it uses the non zoomed size

**Comment by fcsonline** [comment]
Do you have the latest code?

**Comment by nkh** [comment]
now I do and it works

I did an upgrade via the plugin manager but it didn't get me to the latest, after removing it and reinstalling it worked, thanks with this one fixed I think it's usable for me
