### ISSUE TITLE
Question: how does multi selection start

### ISSUE THREAD

**Issue by nkh** [fcsonline/tmux-thumbs#82]
in the documentation multi selection is named but I can't see how to get it in tmux

And good job for the rest, I like it.

**Comment by fcsonline** [comment]
That is true. There is not much documentation about it. 

Multi selection in tmux works with `Enter` and then `Space` keys. The first one to select hints and the second one to dump all picked items.

**Comment by nkh** [comment]
that doesn't work for me, I have version 403be0f when I press enter I get out of selection

also selecting with movement keys instead for  shortcuts feels like it's faster to run multiple selections instead.

**Comment by nkh** [comment]
I have installed the latest version and I get the same problem

**Comment by fcsonline** [comment]
Check this out: https://github.com/fcsonline/tmux-thumbs/pull/90

Reopen the issue if is not clear.
