### ISSUE TITLE
Dead pane added after each thumbs call

### ISSUE THREAD

**Issue by freddez** [fcsonline/tmux-thumbs#84]
Hi,
I've installed your plugin with tmux plugins manager on tmux 3.1 (Ubuntu 20.10), and after each thumbs call, a dead pane "[thumbs]" is added  
And I'm using latest stable version of alacritty terminal

**Comment by fcsonline** [comment]
Can you describe the steps to force the bug?

**Comment by freddez** [comment]
My mistake, I had that in my tmux.conf:

# Keep windows around after they exit
set -g remain-on-exit on

Don't know if it is still an issue, but I don't need this option

**Comment by fcsonline** [comment]
Thanks for the information! Added to the README! a18ab2f
