### ISSUE TITLE
Text copied to tmux copy buffer, not clipboard

### ISSUE THREAD

**Issue by JoyceBabu** [fcsonline/tmux-thumbs#86]
When I press the key next to the highlighted text, it is copied to the copy buffer, not the system clipboard. Hence I cannot paste the text to another application, but can paste it within tmux with `Prefix + P` (which is my `paste-buffer` binding).

How can I copy the text to the clipboard?

**Comment by FliegendeWurst** [comment]
You're looking for the [thumbs-command](https://github.com/fcsonline/tmux-thumbs#thumbs-command) option:

    set -g @thumbs-command 'echo -n {} | xclip -sel clip'

**Comment by JoyceBabu** [comment]
@FliegendeWurst Thank you. I am on OSX. It worked after replacing `xclip` with `pbcopy`.

    set -g @thumbs-command 'echo -n {} | pbcopy'
