### ISSUE TITLE
binding thumbs-key to semicolon doesn't work

### ISSUE THREAD

**Issue by vbauerster** [fcsonline/tmux-thumbs#95]
I cannot bind thumbs-key to semicolon.
Tried both `set -g @thumbs-key \;` and `set -g @thumbs-key ';'`.

```
❯ tmux -V
tmux 3.2a
❯ tmux show -g @thumbs-key
@thumbs-key \;
```

**Comment by fcsonline** [comment]
I have been investigating and it looks like a malfunctioning between tmux and bash escaping. The only workaround I found was to add to your `.tmux.conf` this after loading `tmux-thumbs` plugin:

```
bind-key \; thumbs-pick
```

It is the only solution I can give you while we understand what is going on in this escaping mess.

Let me know if it works.

**Comment by fcsonline** [comment]
Closing it. Feel free to reopen it if the proposed solution doesn't work
