### ISSUE TITLE
Showing only single alphabet hints intermittently

### ISSUE THREAD

**Issue by penguininthedesert** [fcsonline/tmux-thumbs#96]
Hi,

Sometimes it shows only single alphabet hints

![image](https://user-images.githubusercontent.com/12493268/133254091-0ecc1501-81cd-4c58-a6ee-93e2544cc7e3.png)

The screenshot above shows that it works fine but randomly, it shows like blow.

![image](https://user-images.githubusercontent.com/12493268/133254246-b8eae9fb-97a2-4536-a7c8-7fc2dff475a3.png)

As you can see, it scrolls up a bit and shows only single alphabets.

Please let me know if you need logs or something

Many thanks

**Comment by penguininthedesert** [comment]
Here is my tmux.conf
```
set -g @thumbs-command 'tmux set-buffer -w {} && tmux display-message \"Copied {}\"'
set -g @thumbs-upcase-command 'tmux set-buffer -w {} && tmux paste-buffer && tmux display-message \"Copied {}\"'
set -g @thumbs-contrast 1
set -g @thumbs-position off_right
set -g @thumbs-hint-fg-color red
```

**Comment by fcsonline** [comment]
Sorry, I don't understand the issue. This is the correct behavior for tmux-thumbs.

Showing one or two letters depends on the number of matches tmux-thumbs finds out in the current viewport. If the number of matches is bigger than the number of available letters in the alphabet, tmux-thumb will start showing two letters.

If you want to know how those two letters are generated you can read more about n-ary-huffman algorithm. It follows a similar apporach.

**Comment by penguininthedesert** [comment]
Sorry for the lack of explanation.

The screenshots above are the result of running thumbs in the same pane under the same conditions. 
Please check the following video. I tried thumbs 3 times ( prefix + Space and then enter )
https://user-images.githubusercontent.com/12493268/133335540-665ed337-6e2e-427f-ac99-3c25e03246fd.mp4

+ It seems to occur when the tmux panel is split.

Thanks

**Comment by fcsonline** [comment]
Sorry but I continue not understanding the issue. The two screenshots you pasted before have a different viewport, so they have different number of matches.

**Comment by penguininthedesert** [comment]
@fcsonline Did you see the footage? 

https://user-images.githubusercontent.com/12493268/133335540-665ed337-6e2e-427f-ac99-3c25e03246fd.mp4

**Comment by fcsonline** [comment]
Why do you press enter after triggering tmux-thumbs? The most common use case is to choose de hint letter or the upcase hint letter.

**Comment by penguininthedesert** [comment]
I pressed enter to get out of the thumbs mode. Simply, (thumbs -> out) X 3 times. The footage shows that the last try looks different.
I tried with the ESC key but I got the same result.

**Comment by fcsonline** [comment]
Really hard to handle this bug remotely just watching a video. Sorry. If you detect some behavior when this happens, it will be nice to have more information. If you have time to check the source code and investigate why this is happening it will be great.

**Comment by penguininthedesert** [comment]
What information do you need more?
