### ISSUE TITLE
Position of buffer change

### ISSUE THREAD

**Issue by aprowe** [fcsonline/tmux-thumbs#98]
I have noticed that when I use thumbs, the annotated buffer sometimes moves up a line. It seems to compound on itself, and the more times I use thumbs the more the thumbs buffer is off. This happens in copy mode. If I use thumbs in non-copy mode, the thumbs buffer is in the correct location, but when I return from it, my regular buffer moves up a line. 

Maybe it's to do with my 2 line prompt?

Familiar with rust and TUIs, happy to try to fix if given a hint what could be causing it. 

btw Love this plugin! been using it for a while to open paths in a separate pane with `nvr`.

**Comment by fcsonline** [comment]
> Maybe it's to do with my 2 line prompt?

Can you confirm this? It will be really helpful, to spot the bug.

**Comment by aprowe** [comment]
ooh it totally is.
But I know I saw this before I switched to a two-line prompt. Looks like things get whacky if a tmux pane is shortened so some of the lines are soft-broken into two lines. 

My use case is basically editor in left column and build command in a narrow right column, and I use tmux-thumbs to open a file from the build output. Since the column is narrow, some lines are soft-broken and then tmux-thumbs becomes inconsistent with the jumping behavior, depending on how many lines are soft-broken.

**Comment by fcsonline** [comment]
How can we have a test case to play with it an try to solve it?

**Comment by fcsonline** [comment]
Closing it. Feel free to reopen it.

**Comment by ghostbuster91** [comment]
@fcsonline I believe I've just ran into the same issue. For me though it occurs even when not in the copy-mode. 
![Peek 2022-11-07 11-13](https://user-images.githubusercontent.com/5662622/200285109-9c5d675c-3933-4f64-a4ec-6930b25cf2ad.gif)

I use tmux-thumbs version 0.7.1
